### ISSUE TITLE
Extend table component to support row expansion

### ISSUE THREAD

**Issue by jlhogan** [ctoec/component-library#44]

**Comment by mmazanec22** [comment]
@RyanHansz how would you feel about just using [the table library's built in detail panel](https://material-table.com/#/docs/features/detail-panel)?  The expand button is in a different place than the design shown in https://github.com/ctoec/data-collection/issues/133 but otherwise it seems to do what we want.

**Comment by jlhogan** [comment]
@mmazanec22  my bad -- this is done! https://github.com/ctoec/component-library/pull/45 material table ended up being not actually the thing we need

**Comment by jlhogan** [comment]
see https://github.com/ctoec/data-collection/pull/155
